/**
 * DS Icon — maps the TOLBI design-system icon names (kebab-case, from
 * `_ds_bundle.js`'s Icon component) onto lucide-react-native glyphs.
 */
import {
  MapPin, User, Users, ChevronRight, ChevronDown, ChevronUp, ChevronLeft,
  ArrowLeft, ArrowRight, ArrowUpRight, Lock, Mail, Eye, EyeOff, Settings,
  Search, Zap, X, AlertTriangle, AlertCircle, CheckCircle, Check, Image as ImageIcon,
  Bell, Grid3x3, Map, Download, Upload, File, FileText, BookOpen, LogOut, Home,
  Pencil, Camera, Plus, Minus, Calendar, Clock, TrendingUp, TrendingDown,
  Droplet, Droplets, Sun, Cloud, CloudRain, Leaf, Sprout, Layers, Navigation,
  Crosshair, RefreshCw, Wifi, WifiOff, Phone, MessageCircle, Share2, MoreHorizontal,
  Info, Target, Activity, BarChart3, PieChart, Fingerprint, CreditCard, ShieldCheck,
  Thermometer, Wind, QrCode, ScanLine, Play, Send, Wallet, Package, Sparkles,
  ListChecks, ClipboardList, HelpCircle, CircleDot, Bookmark, Star, Trash2, Edit3,
  ShoppingCart, Truck, Banknote, Ruler, Maximize2, PlusCircle, Delete,
} from 'lucide-react-native'
import type { ComponentType } from 'react'

type IconProps = { size?: number; color?: string; strokeWidth?: number }

const MAP: Record<string, ComponentType<any>> = {
  'marker-pin': MapPin,
  user: User,
  users: Users,
  'chevron-right': ChevronRight,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  lock: Lock,
  mail: Mail,
  eye: Eye,
  'eye-off': EyeOff,
  settings: Settings,
  search: Search,
  zap: Zap,
  'x-close': X,
  x: X,
  'alert-triangle': AlertTriangle,
  'alert-circle': AlertCircle,
  'check-circle': CheckCircle,
  check: Check,
  image: ImageIcon,
  bell: Bell,
  grid: Grid3x3,
  map: Map,
  download: Download,
  upload: Upload,
  file: File,
  'file-text': FileText,
  'book-open': BookOpen,
  'log-out': LogOut,
  home: Home,
  edit: Edit3,
  'edit-pencil': Pencil,
  camera: Camera,
  plus: Plus,
  'plus-circle': PlusCircle,
  'help-circle': HelpCircle,
  minus: Minus,
  calendar: Calendar,
  clock: Clock,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  droplet: Droplet,
  droplets: Droplets,
  sun: Sun,
  cloud: Cloud,
  'cloud-rain': CloudRain,
  leaf: Leaf,
  sprout: Sprout,
  layers: Layers,
  navigation: Navigation,
  crosshair: Crosshair,
  refresh: RefreshCw,
  'refresh-cw': RefreshCw,
  wifi: Wifi,
  'wifi-off': WifiOff,
  phone: Phone,
  'message-circle': MessageCircle,
  share: Share2,
  'more-horizontal': MoreHorizontal,
  info: Info,
  target: Target,
  activity: Activity,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  fingerprint: Fingerprint,
  'credit-card': CreditCard,
  shield: ShieldCheck,
  'shield-check': ShieldCheck,
  thermometer: Thermometer,
  wind: Wind,
  'qr-code': QrCode,
  scan: ScanLine,
  play: Play,
  send: Send,
  wallet: Wallet,
  package: Package,
  sparkles: Sparkles,
  'list-checks': ListChecks,
  clipboard: ClipboardList,
  bookmark: Bookmark,
  star: Star,
  trash: Trash2,
  cart: ShoppingCart,
  truck: Truck,
  banknote: Banknote,
  ruler: Ruler,
  maximize: Maximize2,
  'circle-dot': CircleDot,
  delete: Delete,
}

export function Icon({
  name,
  size = 20,
  color = '#101828',
  strokeWidth = 2,
}: IconProps & { name: string }) {
  const Cmp = MAP[name] ?? HelpCircle
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} />
}

export type DsIconName = keyof typeof MAP
